version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tedious
    versions:
    - 11.0.1
    - 11.0.3
    - 11.0.4
    - 11.0.5
    - 11.0.6
  - dependency-name: generic-pool
    versions:
    - 3.7.1
    - 3.7.2
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: chai-datetime
    versions:
    - 1.7.0
